### ISSUE TITLE
Recommended Information Extraction Method for PDF-Resumes?

### ISSUE THREAD

**Issue by MichaelRinger** [tstanislawek/awesome-document-understanding#2]
Hello,

I know this isnt a issue, but i couldnt find a better place to ask this question.

I guess extracting data from resumes belongs to the key-information-extraction area.
So for the start I thought about using just a normal BERT and in my training data I only mark the entities that want to extract. But does it also makes sense to create a label for the label "english" (see example below) to get better results or to use relation extraction at this semi-form like data? Or does the behaviour of BERT recognizes automatically that after the string "english: " is going be a grade?

For a simple example at extracting grades from a resume:
input:
"english: 2"
-> do i need only need to annotate "2" or is it recommended to do something else

output:
grade_english: "2"

wanted labels:
- firstname 
- lastname
- last_job_title
- graduation
- grade_english
- grade_math
- grade_economy

**Comment by tstanislawek** [comment]
Hello,

ideal case could be to at first annotate your dataset on document-level (not on the token-level), because you will find out what strategy is the best for KIE problem: using sequence labeling or seq2seq models. 

In the sequence labeling case, you must also add annotation on the token level (but you could also use different strategies for annotation some datapoints - in your case `grade_english`). Proposed strategy is a good starting point, but if you don't try others annotation strategies it hard to predict which token-level annotation strategy is the best one.

Personally I thins seq2seq models are much more flexible.

**Comment by MichaelRinger** [comment]
Thanks for your answer.
How can be seq2seq models used NER without annotating tokens?
What should I annotate from my training data to be able to test later on without reannotating?
Which open source annotation tool would you recommend me?

**Comment by tstanislawek** [comment]
> How can be seq2seq models used NER without annotating tokens?
Please, check this paper: https://arxiv.org/abs/2102.09550

> What should I annotate from my training data to be able to test later on without reannotating?
Nothing, you should just normalize in the same way entities (e.g. text span "7rd of May 2012" should be changed into "2012-05-07")

> Which open source annotation tool would you recommend me?
A) https://labelstud.io/
B) https://github.com/allenai/pawls
